version: '1'
services:
  student-service:
    image: student-service:v1
    depends_on:
    - discovery
  discovery:
    image: eurekaserver:v1
    ports:
    - "8761:8761"
  apigateway:
    image: zuulgateway-docker:v1
    depends_on:
    - discovery
    ports:
    - "8082:8082"